### ISSUE TITLE
Rename the project?

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#101]
sexpr-wasm-prototype is a very old name for the project, and doesn't really reflect what it is or does. Any ideas for a better name?

**Comment by dschuff** [comment]
We may end up wanting to use it in some cases where we currently use binaryen if Binaryen's IR diverges from wasm proper.

So currently it's a text/binary encoder/decoder, an interpreter, and... anything else? Sort of analogous to binutils, but I wouldn't necessarily want to call it something derived from 'binutils' exactly unless we want to provide all those tools. Does sexpr-wasm do much handling or dumping of the various non-code sections currently? Other tools might include dumping the names section if it exists (a la nm), and maybe even more arbitrary sectiony stuff like objcopy.
We could do more of that, although I had thought we might want do some of that with LLVM, which has a lot of common infrastructure which would make it easier (and more accessible to boot). Although maybe it does make sense to have something more standalone too? e.g. if we have users of sexpr-wasm who like that property (being standalone). I guess readelf and bfd have existed side-by-side for years, so why not this too :)

If we don't want to be 'binutils' we could say wasm-utils or wasm-tools, but that's pretty generic. Even a wasm-binutils or wasm-binary-tools or some such doesn't quite capture it since it has an interpreter :)

**Comment by binji** [comment]
> So currently it's a text/binary encoder/decoder, an interpreter, and... anything else?

It can generate a JavaScript test file from a spec test. But yeah, not much else. sexpr-wasm is basically just a C implementation of ml-proto.

> Does sexpr-wasm do much handling or dumping of the various non-code sections currently?

Yes, it can read or write the names section w/ a flag. Otherwise it strips it. I think it's reasonable to support other non-code sections too, when they come along.

>  if we have users of sexpr-wasm who like that property (being standalone).

I think some users do like that it is standalone and relatively simple. At least, I do. :)

> Even a wasm-binutils or wasm-binary-tools or some such doesn't quite capture it since it has an interpreter :)

I guess that's the nice thing about picking a non-descriptive name -- you can make it do whatever you want :P

**Comment by dschuff** [comment]
`tool-utils` is is then!

**Comment by titzer** [comment]
WASM binary toolkit? Then again, I'm a fan of cutesy names, so maybe
Wabbit? :-)

**Comment by dschuff** [comment]
WebAssembly Toolkit (WAT?)

**Comment by binji** [comment]
I was thinking about it, and the main differentiating factor is that it is written in C. So maybe just `c-utils` or `c-tools`. Another nice thing is that it unlikely anyone else would write in C. :-)

That said, `wabbit` and `WAT` are pretty great too. :D

**Comment by titzer** [comment]
I'm voting all my TL points for Wabbit, however many that is :-D

**Comment by binji** [comment]
Derek and I have started calling it Wabbit. Let's go ahead and make that change :)

**Comment by s3ththompson** [comment]
Renamed the repo!

Looks like the next steps are:
- [ ] Merge #111 to change name in `README.md`
- [ ] Change name in `design/TextFormat.md`
- [ ] Fix Travis CI (I didn't look at this too hard yet, but it looks like it doesn't see `wabt` yet)
- [ ] Send mail to others affected by this change

**Comment by binji** [comment]
Looks like Travis CI is working again.
Renaming design/TextFormat.md in https://github.com/WebAssembly/design/pull/808.

**Comment by binji** [comment]
This seems to be done. Who needs to be mailed? @s3ththompson can you do this?

**Comment by binji** [comment]
Oh, and can you change the project description too? It still says "sexpression -> wasm" :-)

**Comment by s3ththompson** [comment]
Updated description and sent out the name change to the other browsers as an FYI.
