### ISSUE TITLE
The result of wasm2wat is not real s-expression

### ISSUE THREAD

**Issue by NalaGinrut** [WebAssembly/wabt#1048]
Hi there!
I found that the result of wasm2wat is not real s-expression, the "if-else" branching code is an indentation-based syntax just like Python. This inconsistency makes it harder to use Lisp-like languages (for example, Scheme) to implement a static analyzer. It means people have to write a specific parser for it.

For example:

```scheme
  (func $_main (type 5) (result i32)
    (local i32 i32 i32 i32)
    global.get 14
......
    i32.ge_s
    if  ;; label = @1
      i32.const 16
      call $abortStackOverflow
    end
......
    return)
```

An ideal form should be:

```scheme
  (func $_main (type 5) (result i32)
    (local i32 i32 i32 i32)
    global.get 14
......
    i32.ge_s
    (if  ;; label = @1
       i32.const 16
       call $abortStackOverflow)
......
    return)
```

This shouldn't be hard to implement in the current wabt, what do you think?

Thanks!

**Comment by jgravelle-google** [comment]
First (and this is mostly pendatry), just because `if`s aren't modeled as a sub-list doesn't mean that they're not "real" s-expressions. And I don't know how one would avoid wasm-specific parsing logic when implementing a static analyzer, though maybe it's easier currently because if/block/loop can't take arguments yet.

Second, wabt does have support for folded expressions, `wasm2wat --fold-exprs` does fold the block contents into a sub-sexpr.
Note still that not all expressions are fold-able, so to support wasm in full generality a tool would need to understand the unfolded expressions. Most constructs are representable though, so supporting just folded expressions is still a good way to start.

**Comment by NalaGinrut** [comment]
@jgravelle-google Yes, it's required to parse wasm-specific logic for a static analyzer, but if I write yet another specific parser, why should I bother to use wasm2wat? I think people use wasm2wat because they don't want to do redundant work, no?

**Comment by jgravelle-google** [comment]
The output of wasm2wat should be parseable by lisp's `read` either way, it's just a question of ergonomics as to how that output is structured.

Does `--fold-exprs` suffice? Or is there more work that needs to be done?

**Comment by NalaGinrut** [comment]
@jgravelle-google I've tried ```--fold-exprs```, it looks like what I need:
```scheme
 (func $stackAlloc (type 1) (param i32) (result i32)
...
    (if  ;; label = @1
      (i32.ge_s
        (global.get 14)
        (global.get 15))
      (then
        (call $abortStackOverflow
          (local.get 0))))
    (return
      (local.get 1)))
```

Thanks! I'll try it, and I may feedback if any possible.
