### ISSUE TITLE
Allow building with system gtest and ply

### ISSUE THREAD

**Issue by ids1024** [WebAssembly/wabt#1103]
`gtest` and `ply `seem to be packaged by Arch and Alpine (and presumably other distros, though perhaps not all). Is it necessary have them vendored as submodules?

It seems desirable for packaging to either not provide a vendored version, or have an option to use the system version instead.

**Comment by ids1024** [comment]
A test implementation for (unconditionally) using the system version of gtest: https://github.com/ids1024/wabt/commit/c497ff11b356720ca02cd63499673f03eacd87fb

This works on Arch. Not on Alpine, since `gtest_main.cc` isn't packaged. Perhaps it isn't possible to rely on that being packaged (and in a consistent place), but it's a small enough file to duplicate (7 non-comment lines).

**Comment by binji** [comment]
Having gtest and ply as submodules makes it easier to build and test. Otherwise I may run into various version incompatibilities, etc. Both libraries are used only for development/testing of wabt, and not used for the final installed executables. So I'm not sure if it is all that useful to use the system versions here. If so, we can provide an option, though it wouldn't be the default so it's likely to break over time unless maintained.
