### ISSUE TITLE
Source names in wasm-interp --trace

### ISSUE THREAD

**Issue by ljulliar** [WebAssembly/wabt#1127]
HI all,

I'm currently writing wat code and using wat2wasm to compile wat source code to wasm binary format. I was wondering if there is a way to tell wasm-interp to use the original source names when tracing the execution (--trace option). I initially though the --debug-names option in wat2 wasm would serve that purpose but apparently not.

Is there any way to achieve this ?
Thank you for your help.

Laurent

**Comment by binji** [comment]
No, there's no way to do this currently. It's not trivial either, since by the time the interpreter is running, all functions from all modules have been combined into one instruction stream. I think the way to make this work would be to provide a data structure on the side that knows how to map from the instruction stream index back to its original function name+offset. I started to look into this, but unfortunately don't have time to add this functionality right now.
