### ISSUE TITLE
Omitting the data count section to remain MVP-compatible?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/wabt#1189]
Currently `wat2wasm` will [unconditionally emit the data count section](https://github.com/WebAssembly/wabt/blob/f157909d791ea8f32248657062e8fdb3ed435eb5/src/binary-writer.cc#L1061-L1065) if the bulk memory feature is enabled, but I was wondering if a better heuristic might be to omit the section unless there are instructions that require the data count section? Otherwise as bulk memory gets enabled by default wabt will switch to by default producing non-MVP compatible wasm modules, and it could take some time for all runtimes/consumers/etc to update to the post-MVP world.

**Comment by tlively** [comment]
What's a situation where the bulk memory feature flag is passed but the binary is expected to be MVP compatible? My guess is that the feature set of the input is unknown but is expected to be unchanged in the output. In that case this sounds like a job for the [target features section](https://github.com/WebAssembly/tool-conventions/blob/master/Linking.md#target-features-section) rather than a feature flag.

**Comment by alexcrichton** [comment]
Oh my thinking is that eventually (perhaps soon?) the bulk memory flag won't be needed. Today you're right the logic is fine, but I'm wondering about the ux when it's enabled by emdefault

**Comment by tlively** [comment]
That raises the larger question of how default feature sets should change, and I don't think we've decided on an answer to that.

But supposing the default did change to include bulk memory, shouldn't users be passing a flag to disable bulk memory if they're targeting engines that don't support it? I don't see much value in fortuitously being MVP compatible when the user does not ask for it. If the user cares about MVP compatibility, they will ask for it.

I guess it's not a big deal if a tool wants to do the small amount of extra work to be MVP-compatible when possible, but I just wouldn't want to set an expectation that all tools will work that way.

**Comment by alexcrichton** [comment]
The use case motivating this issue is writing wasm tooling today and using wabt as a regression test suite. The passing of feature flags doesn't work for all tooling and none of the tools I've written so far require feature flags for wasm features. It's difficult to test binary encoding against wabt because the tooling all infers whether the data count section is necessary but wabt has a different heuristic

While some users have total knowledge of all their tooling and versions and such I think it's pretty reasonable for standard tooling to try to be as flexible as possible, for example here inferring whether the data count section is necessary.

I won't really press for this though, if y'all don't think this is worthwhile I'll figure out some way to work around it

**Comment by tlively** [comment]
Does your tooling generate (or preserve) the target features section? That does sound like a good use case for it, since it accomplishes the same thing as heuristics but is more explicit. I don't think wabt supports the target feature section at the moment, but it probably should.

**Comment by alexcrichton** [comment]
I don't think this is a great use for the target features section because it's not guaranteed to be present, and the presence of bulk memory instructions doesn't requite the target feature section. 

The tooling I've been working on that handles this is:

* [walrus](https://github.com/rustwasm/walrus) which is used to parse and perform transformations on a binary wasm module
* [wast](https://github.com/alexcrichton/wast) which is a Rust parser for `*.wat` files

Developing the latter has no precedent for emitting a target features section and requires a number of adjustments to the binary format to ensure that its binary format agrees with wabt's

**Comment by tlively** [comment]
> Developing the latter has no precedent for emitting a target features section and requires a number of adjustments to the binary format to ensure that its binary format agrees with wabt's

Can you elaborate on that? It's true there's no way currently to specify the target features section in text, but binaryen for example can take a wast input and a set of feature flags and produce a binary that contains a target features section reflecting those flags. In Binaryen we always use feature flags if present or otherwise fall back to the target features section. That means that flags must be used in the case of non-MVP modules without a target features section. The philosophy behind this decision is that toolchains should be as predictable as possible and not do work to try to infer implicit meaning.

Also, while its true that arbitrary binaries may not have a custom features section, those emitted by lld are guaranteed to have one or be MVP binaries. I don't know if that's a strong enough guarantee to be useful, though.

**Comment by alexcrichton** [comment]
For the use cases we have at least we didn't want to fiddle with feature flags and instead wanted to make the tooling amenable to future wasm features if used but work without them as well. In that sense for a wat file parser we don't have any extra input for what features to enable or what section to emit. It's certainly possible to add, but it's one I'd personally prefer not to.

Again though if wabt's position is that it doesn't want to do this, that's ok!

**Comment by binji** [comment]
I agree that it would be nice to be MVP-compatible where possible, even when a flag is passed. I did something similar here: https://github.com/WebAssembly/wabt/pull/1286. It doesn't seem like it would be too difficult in this case to omit the data count section when it's not required.

**Comment by binji** [comment]
Fixed in #1312.
