### ISSUE TITLE
[wat2wasm] directive @inline for preprocessor

### ISSUE THREAD

**Issue by munrocket** [WebAssembly/wabt#1260]
Function inlining can increase performance in x2 for different algorithms. But readability become worsens after that. I suggest to create a some directive for `wat2wasm` preprocessor.
```webassembly
;;@inline
(func $add (param $a f64) (param $b f64) (result f64)
  (f64.add (get_local $a) (get_local $b))
)
```

**Comment by tlively** [comment]
I'm not sure WABT needs to support optimizations like this, since its primary purpose is to inspect modules and perform format conversions between them. https://github.com/webassembly/binaryen has a WebAssembly optimizer and would probably be a better tool if you're looking to optimize your modules.

**Comment by munrocket** [comment]
Probably you right, just wonder that it's so costly to performance sometime.

**Comment by binji** [comment]
Thanks for your interest! But yeah, this is outside the scope of wabt, so closing.
