### ISSUE TITLE
Don't require Python in build (if not found, skip those targets)

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#1385]
The current build requires python 3.5, which is commonly found on modern *nixes, but may not be installed on Windows, Mac, etc. It's only used for running tests, so it would be nice to fail gracefully if python isn't available instead of preventing the build to proceed.

**Comment by lkarthee** [comment]
I have submitted a PR for this - https://github.com/WebAssembly/wabt/pull/1392

**Comment by sbc100** [comment]
We already have `-DBUILD_TESTS=OFF` which should remove the requirement.  

We could make the error message nicer maybe?  Something like: `python3 not found, either install it or build with -DBUILD_TESTS=OFF`.

**Comment by binji** [comment]
@aardappel originally mentioned the issue in #1385 to me, primarily because the version of Python3 was not immediately available on Windows, and isn't needed unless you want to test. I figured that it would be a nice fallback to automatically. But perhaps a better error message is OK too. Wouter, what do you think?

**Comment by sbc100** [comment]
What do you mean by "not immediately available on Windows"?  Is there some version we could switch to that would be more immediately available?

I guess we could have `BUILD_TESTS` automatically default of `OFF` if python isn't found, but it seems reasonable to ask people to opt out explicitly.

**Comment by binji** [comment]
> What do you mean by "not immediately available on Windows"? 

Not sure, I'm probably just incorrectly echoing Wouter's comments about this. I agree that a better error message is probably enough here.

**Comment by aardappel** [comment]
This particular machine only had Python 2.7 installed, so CMake failed. It's a bit odd for CMake to fail on a tool that's only required if I decide to run tests.

I should generally be able to build C++ binaries with a C++ build system without requiring Python.

**Comment by lkarthee** [comment]
Is there a specific reason why python > 3.5 is needed to run tests?  Will scripts fail if python3 < 3.5 is used ?

**Comment by binji** [comment]
We switched from Python2 to Python3 recently, and I believe we chose Python 3.5 because of some nice feature it had... though to be honest I can't remember what that was. Something to do with formatting byte strings perhaps?

**Comment by sbc100** [comment]
Python2 is officially deprecated and unmaintained, and that is a cost to maintaining support for both.

Dropping python2 support doesn't effect our actual users since they can just build with `-DBUILD_TESTS=OFF`.  It only effects core developers who actually want to run the tests.  So, the impact of switch here is minimal, compared a project that actually has python as part of the product.

**Comment by lkarthee** [comment]
Python2 to 3 switch is only a question of when. I was curious about why python3 >= 3.5, instead of python3.

**Comment by sbc100** [comment]
I don't remember why we picked 3.5.   The comment says "Python 3.5 is the version shipped in Ubuntu Xenial".

I guess we could support older python 3 versions if anyone cares.   We should probably try to test against the oldest version we support to keep us honest.    Maybe that is what inspired my xenial comment, since that is the version of linux we use of travis right now.

**Comment by aardappel** [comment]
In addition, I think all Python scripts should check what version they run on as first thing they do, and bail out with a clear message. If you currently run the tests with Python 2.7, you get a lot of them failing with various type errors, and it will not be immediately obvious (to me, anyway, not a Python user) that this is due to the wrong version.
