### ISSUE TITLE
Convert tests from AST format to new "flat" format

### ISSUE THREAD

**Issue by binji** [WebAssembly/wabt#139]
All of the internal tests are written using the old style, but should be converted to the new style, e.g.:

old style:

```
(func (result i32)
  (local i32)
  (block i32
    (i32.add (i32.const 1) (get_local 0))))
```

new style:

```
(func (result i32)
  (local i32)
  block i32
    i32.const 1
    get_local 0
    i32.add
  end)
```

**Comment by citisolo** [comment]
I would like to pick this one up , is there a spec or discussion for the new format ?

**Comment by binji** [comment]
This doc should be accurate: https://github.com/WebAssembly/spec/tree/master/ml-proto#s-expression-syntax

**Comment by binji** [comment]
BTW, I'd suggest if you take this on to update the tests in batches, rather than all at once. It will be nicer to review.

**Comment by citisolo** [comment]
#166

**Comment by binji** [comment]
No, all tests should be updated to this format. This is a good start though!

**Comment by citisolo** [comment]
just wanted to run this by you , should I lay it out this way
```
(module
  (func                ;; depth
    block $outer       ;; 4
      loop             ;; 2 loop, 3 exit
      block            ;; 1
      i32.const 0
      drop 
      block $inner     ;; 0
      br 0
      br 1
      br 2
      br 3
      end
      end
      end
    end))
```

or this way;
```
(module
  (func                     ;; depth
    block $outer           ;; 4
      loop                 ;; 2 loop, 3 exit
        block              ;; 1
          i32.const 0
          drop 
          block $inner     ;; 0
            br 0
            br 1
            br 2
            br 3
          end
        end
      end
    end))
```

**Comment by rossberg-chromium** [comment]
Just wondering, is there a strong reason to change the tests? We intentionally decided to continue supporting the existing syntax as built-in "macros".

As for layout, I suggest indenting.

**Comment by citisolo** [comment]
Well, I'm new here so I can't really speak too much on the need for this change but I will say , as a newbie looking at the tests to familiarize myself with webassembly , the new syntax is a lot easier on the eye for instance this;  
```
(module
  (func
    i32.const 0
    i32.const 0
    i32.rotr
    i32.const 0
    i32.rotl
    i32.const 0
    i32.shr_s
    i32.const 0
    i32.shr_u
    i32.const 0
    i32.shl
    i32.const 0
    i32.xor
    i32.const 0
    i32.or
    i32.const 0
    i32.and
    i32.const 0
    i32.rem_u
    i32.const 0
    i32.rem_s
    i32.const 0
    i32.div_u
    i32.const 0
    i32.div_s
    i32.const 0
    i32.mul
    i32.const 0
    i32.sub
    i32.const 0
    i32.add
    drop ...
```
is a whole lot more palatable than this;
```
 (module
   (func
    (drop
      (i32.add
        (i32.sub
          (i32.mul
            (i32.div_s
              (i32.div_u
                (i32.rem_s
                  (i32.rem_u
                    (i32.and
                      (i32.or
                        (i32.xor
                          (i32.shl
                            (i32.shr_u
                              (i32.shr_s
                                (i32.rotl
                                  (i32.rotr
                                    (i32.const 0)
                                    (i32.const 0))
                                  (i32.const 0))
                                (i32.const 0))
                              (i32.const 0))
                            (i32.const 0))
                          (i32.const 0))
                        (i32.const 0))
                      (i32.const 0))
                    (i32.const 0))
                  (i32.const 0))
                (i32.const 0))
              (i32.const 0))
            (i32.const 0))
          (i32.const 0))
        (i32.const 0)))
```

**Comment by rossberg-chromium** [comment]
@citisolo, agreed for this example, but that's a fairly degenerate case. In most ordinary cases I would expect the nested form to be more readable.

**Comment by binji** [comment]
@rossberg-chromium I think the flat format is easier to understand for complex cases because it more clearly maps to the behavior of the stack machine  (I often found myself taking the examples in https://github.com/WebAssembly/spec/pull/345 and converting them in my head so I could understand them better). It also has a direct mapping to the binary format, everything else is sugar. And as @citisolo mentions, it is less visually noisy. 

I'm also concerned that the AST-like format has the potential to confuse readers, considering it used to be an AST. And the format gets strange in edge cases, e.g. `(i32.const 1) (i32.add (i32.const 2))`. I assumed that we kept the s-expression around primarily as a concession to binaryen, and to prevent having to write the spec tests. Honestly, I'd prefer switching everything over to the new format and dropping the sugar. But since that won't happen, at least we can make the wabt tests nicer (the ones that aren't eventually subsumed by the spec tests, that is).

**Comment by dschuff** [comment]
I think I'd prefer having the flat format wherever possible too. I can definitely see how the sugared/folded format is nicer for hand-writing tests, but I think for most other purposes it hurts more than it helps. For reading (at least for the purposes of those who are reading it today and in the next couple of months) I think it's better to more directly reflect the stack-machine semantics, and the form that browsers will be displaying at launch. Also for those who will soon be reading the spec, some of them may want to write their own parsers or conversion tools, and I think supporting all the extra sugar would make it considerably more work. Come to think of it, it would be nice to have the macro layer in more explicit form, and an external tool so that someone could write a simple parser for the linear form but still support the spec tests if they are going to continue to be macro-ed.

I think that would be great even for Binaryen. Support for the expressionized and linear text makes the parser way more complicated (admittedly this is from me reading Alon's code rather than writing it myself). I would guess that even if we wanted to keep an AST format for Binaryen's IR, it would be better to have 2 parsers; one that only supports linear IR and the other that only supports Binaryen's AST in sexpr form. That would be quite easy to implement if there were a standard macro-conversion tool.

**Comment by citisolo** [comment]
@binji The internal tests seem to be converted , do you want the third-party test-suite to be updated too?

**Comment by binji** [comment]
Nope, those are mirrored from the spec repo. Those need to stay as sexpr-style for now so they can be used by binaryen. Thanks for doing this!
