### ISSUE TITLE
Wrong opcode for v8x16.shuffle?

### ISSUE THREAD

**Issue by libwasm** [WebAssembly/wabt#1390]
The proposal document describes the  opcode for v8x16.shuffle as 0xfd 0xc1,

The wabt tools however use the code 0xfd 0x03.

Which one is rightt?

**Comment by tlively** [comment]
You should use `0x03`, since that's the opcode used by most tools and engines. At some point the shuffle opcode got updated in the spec, but there was not a critical mass of implementations that switched to using the new opcode. Note that we are planning a larger renumbering to happen soon in https://github.com/WebAssembly/simd/pull/209, and at that point the entire ecosystem will have a coordinated update.

**Comment by libwasm** [comment]
Thanks, I will do that,
