### ISSUE TITLE
[wat2wasm] requires alignments be a power of two, which is incorrect

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/wabt#1567]
I'm using `wat2wasm`. The version is reported as `1.0.13 (1.0.19)` (I installed WABT with `brew`). I'm compiling handwritten WAT code.

If I load or store a (correctly aligned) 64-bit value with `align=3`, WABT incorrectly complains:

``` html
<location> error: alignment must be power-of-two
    f64.load align=3
```

Using `align=4` fixes the issue, but the spec only permits alignment values of `0`, `1`, `2` and `3` (for 8-bit, 16-bit, 32-bit and 64-bit, respectively):

> Memory is accessed with load and store instructions for the different value types. They all take a memory immediate memarg that contains an address offset and the expected alignment **(expressed as the exponent of a power of 2)**.

**Comment by carlsmith** [comment]
I tried using `align=4` for 32-bit values, and `align=8` for 64-bit values. That seemed to work too, so I'm not sure how WABT is interpreting these numbers.

**Comment by binji** [comment]
This behavior is required by the spec. The text format accepts these values as bytes, but the binary format uses log_2 values. Using a non-power of two value is therefore malformed in the text format since there's no way to specify it in the binary format. Using a larger alignment value is invalid, but should be possible to convert text->binary if you use the `--no-check` flag when converting.

**Comment by carlsmith** [comment]
Thanks @binji. So `align=8` is 64-bit??

**Comment by binji** [comment]
@carlsmith yes, that's correct.

**Comment by carlsmith** [comment]
Thank you, @binji. Much appreciated.
