### ISSUE TITLE
MAP_ANONYMOUS undefined on OS X 10.10 and earlier (pre-2015)

### ISSUE THREAD

**Issue by jakirkham** [WebAssembly/wabt#1620]
Seeing the following error when compiling macOS. It appears the `MAP_ANONYMOUS` flag may not be defined, but perhaps [`MAP_ANON`]( https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/mmap.2.html ) would be a good substitute

```
../wasm2c/wasm-rt-impl.c:133:58: error: use of undeclared identifier 'MAP_ANONYMOUS'
      mmap(NULL, 0x200000000ul, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0);
                                                         ^
1 error generated.
```

**Comment by jakirkham** [comment]
Any thoughts on this issue?

**Comment by jakirkham** [comment]
Sorry to keep bumping this. We are unable to build on macOS ever since this issue surfaced. Any help here would be appreciated :)

**Comment by sbc100** [comment]
Looks like an easy fix.  I'm confused why this isn't causing a built failure during CI.  I will take a look.

**Comment by sbc100** [comment]
Odd .. I can see wasm-rt-impl.c being compiled just fine by the github CI https://github.com/WebAssembly/wabt/runs/3257150141#step:10:18.

**Comment by keithw** [comment]
Closing as dormant and "works in CI." Please reopen or comment if somebody is still having trouble here.

**Comment by jakirkham** [comment]
This issue is still present. Please reopen.

Here's [a recent build log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=570220&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b ) demonstrating the issue when our downstream patch is removed ( https://github.com/conda-forge/wabt-feedstock/pull/25/commits/65ee0ea7a631051f4e829c9dbb8c5578f5a63a82 ).

All it would take for one to fix it would be to define `MAP_ANON` with `MAP_ANONYMOUS` if only the latter is defined.

**Comment by keithw** [comment]
Ok, reopening and did some Googling.

It looks like MacOS added MAP_ANONYMOUS in 2015 (with the release of El Capitan 10.11). The problem here appears to be that you're compiling with the SDK for Mac OS 10.9, which was released in 2013 and is no longer supported. I'm guessing this is why this hasn't been a problem for most downstream users.

If you want to submit a PR to add support for Mac OS <10.11, I can take a look, but it's going to be hard for us to get test coverage/CI there. Your other options probably include (a) compiling on a more recent version of MacOS, (b) keeping a local patch, or (c) disabling the build of wasm-rt-impl since you're not using it anyway. (It's an example runtime meant to show how to embed wasm2c output in a POSIX-like environment; wabt uses it for running the wasm2c tests but that's it.)

**Comment by keithw** [comment]
Closing as dormant/unresponded-to. We would still take a PR on this.
