### ISSUE TITLE
wabt does not build on Apple M1 computers

### ISSUE THREAD

**Issue by raydelto** [WebAssembly/wabt#1688]
I'm trying to build wabt on an apple M1 computer running Big Sur 11.3.1 and I get this error message:

CMake Warning at CMakeLists.txt:197 (message):
  Unknown target architecture!

**Comment by Sentinent** [comment]
Looks like `file` is reporting `dummy: Mach-O 64-bit executable arm64` which doesn't match the `ARM` line. [`Relevant line`](https://github.com/WebAssembly/wabt/blob/c2aec5aef9a476c5be41525236af259edb6aad6c/CMakeLists.txt#L192) (since MATCH is case sensitive). A dumb workaround that worked for me was just changing
`elseif (${FILE_OUTPUT} MATCHES "ARM")` => `elseif (${FILE_OUTPUT} MATCHES "ARM" OR ${FILE_OUTPUT} MATCHES "arm")`.
