### ISSUE TITLE
warning: ‘index’ may be used uninitialized

### ISSUE THREAD

**Issue by steven-johnson** [WebAssembly/wabt#2020]
Compiling WABT 1.0.30 with gcc 12.2.0, I get the following warning:

```
/usr/include/c++/12/bits/stl_pair.h:665:43: warning: ‘index’ may be used uninitialized [-Wmaybe-uninitialized]
  665 |              || (!(__y.first < __x.first) && __x.second < __y.second); }
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/wat-writer.cc: In function ‘wabt::Result src/wat-writer.cc:1717:9: note: ‘index’ was declared here
 1717 |   Index index;
```

**Comment by sbc100** [comment]
Thats odd because the assignment to `index` happens in the switch/case above.   It gets assigned in every case and if I remove one of the case statement I get `warning: enumeration value 'Tag' not handled in switch [-Wswitch]`.   So can't gcc not see that it the above switch has complete coverage, or is it assuming that the `export_.kind` could be some value outside of the enum?

**Comment by steven-johnson** [comment]
I assumed that it was just a compiler bug, frankly -- it wouldn't be the first time I've seen this kind of warning misfire -- though I didn't look at the code long enough to decide for certain.
