### ISSUE TITLE
Include wasm-rt* source files in binary release packages

### ISSUE THREAD

**Issue by remko** [WebAssembly/wabt#2057]
When using `wasm2c`, the `wasm-rt-*` files are necessary to compile/link the resulting program. The WABT binary release packages come with a compiled version of wasm-rt as a static library, but this may not match the target platform for which the `wasm2c` result is used. 

I therefore propose to include the necessary wasm2c runtime files (`wasm-rt-impl.c`, `wasm-rt-impl.h`, and `wasm-rt.h`) in the binary package as source under a `src/wasm2c` subdir. This gives toolchains that use wasm2c the flexibility to compile the wasm2c output for any platform.

Note that the Debian binary package of `wabt` already packages the wasm-rt source files in the WABT package under `/usr/src/wasm2c` (see [the filelist](https://packages.debian.org/sid/amd64/wabt/filelist)).

**Comment by keithw** [comment]
The GitHub binary releases already include wasm-rt.h and wasm-rt-impl.h (see https://github.com/WebAssembly/wabt/blob/main/CMakeLists.txt#L396), so I think if you want to add wasm-rt-impl.c to that list, it would be an easy change.

(I hesitate a little to call the rt-impl files "necessary," because I think of them as just _one example_ of how to implement the rt API, an example that many embedders might take more as a jumping-off point for their own needs instead of as canonical. But we don't have to retread that ground...)
