### ISSUE TITLE
Why is the JS api module- and promise-based? / Alternative non-`Promise` Emscripten compilation path

### ISSUE THREAD

**Issue by Yongbeom-Kim** [WebAssembly/wabt#2138]
I've been looking over at using the wabt JS API, as well as [wabt.js](https://github.com/AssemblyScript/wabt.js).

I'm a little confused about why the compiled wabt toolkit is essentially exported as function that returns a promise which resolves to a `WabtModule` class.

This kinda means that for projects incrementally adopting wabt (as I am currently trying to do), (1) there is no tree-shaking available, and (2) many projects (that build to older ES versions without top-level await support) will need to do some major refactoring to support asynchronous loading of the module.

What confuses me even more is that emscripten api seems to load any wasm function synchronously, without any promises - so this tells me that this promise-module thing is a decision made? 

I'm wondering if there are reasons for why the emscripten compilation has been done this way, and also if you guys are open to alternative build paths that expose and load the wabt functions independently to support synchronous loading and tree shaking. Could anyone help me with this?

**Comment by sbc100** [comment]
Emscripten default to async compilation: https://github.com/emscripten-core/emscripten/blob/33a9cf1bceaaf52229285b6e77bf7f5747b18dba/src/settings.js#L1361-L1367

On the web, in chrome at least, there is a limit of 6Kb for synchronously compiling wasm modules.   So under the hood at least that wabt wasm module will need to be loaded async.

In theory we could build a version the `MODULARIZE` and/or `EXPORT_ES6` options that export the static API rather than promise of it, but it would still not be usable/available synchronously (we would have to somehow fail with "no ready" yet, if you try to call it too early.

If you want to try building wabt.js in some other way, and send PR we would consider it.  I don't think anyone is particular attached the way waby.js it built or published.  It was mostly build for the demo web page I believe.   For sure,  most wabt users are not using the JS version.

**Comment by Yongbeom-Kim** [comment]
Apologies for the late reply.

Thank you very much for the context! I understand better now why it is loaded asynchronously

I'll go and see if I can get an alternative build working, but it'll probably take some time haha - let me close this and I'll update yall with a pr if I get something working
