### ISSUE TITLE
[wasm2c] alloca.h

### ISSUE THREAD

**Issue by penzn** [WebAssembly/wabt#2210]
When I try to build on FreeBSD wasm2c tests fail due to lack of `alloca.h` headers (using wasm2c should be problematic because of that). I'm not sure if this happens on other platforms. There are a few potential ways to fix it, for example include `stdlib.h` instead or make the include conditional, either via a preprocessor check in place or by generating the template via CMake.

**Comment by keithw** [comment]
The best way to fix this is probably just to edit src/template/wasm2c.includes.c. Right now it says:

```c
#if defined(_MSC_VER)
#include <intrin.h>
#include <malloc.h>
#define alloca _alloca
#else
#include <alloca.h>
#endif
```

If there's a different header that FreeBSD wants, seems easy to include it here. We probably shouldn't do this in CMake because (at least so far) wasm2c generates the same portable output on any host platform.

**Comment by penzn** [comment]
FreeBSD way of doing it would be to include `stdlib.h`. I can put that under an ifdef or just replace `alloca.h` with it as it would work on other posix systems as well.

**Comment by keithw** [comment]
I think I'd prefer an ifdef for FreeBSD -- Linux's documentation calls for alloca.h, and stdlib is more to pull in if not required.
