### ISSUE TITLE
Mac ARM support

### ISSUE THREAD

**Issue by andreaTP** [WebAssembly/wabt#2366]
Hi 👋  and thanks for the great project!

For generating the tests of our [Java WASM interpreter](https://github.com/dylibso/chicory) we are relying heavily on `wast2json`, sadly there are no releases for Mac ARM, and people need to recompile this project locally to get a working version of the executable.

Do you have any plans to release for Mac ARM?

**Comment by sbc100** [comment]
Can folks use the homebrew version: https://formulae.brew.sh/formula/wabt ?

**Comment by andreaTP** [comment]
Yes we worked around this way for now, unfortunately this way we cannot control the wabt installed version and it can give issues.
It would be nice to have a GH official release of the packages for all of the architectures.

**Comment by sbc100** [comment]
If you would like to contribute a github CI recipe to publish an arm64 macOS build that would be most welcome.

**Comment by andreaTP** [comment]
Make sense, unfortunately, I'm extremely not familiar with this project build and tools, I have attempted to use the new [apple silicon runners](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) but they are available only for enterprise accounts.

It should be anyhow possible to do something with Qemu or similar, it would be great if you have any reference or link to spare to get me started @sbc100 🙏

**Comment by kgantchev** [comment]
@andreaTP Hi, I'm the CEO and co-founder of FlyCI.  You can also try the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. We have a free tier of 500 minutes/month on M1.

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Exclusive M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```
 
They're up to 2x faster and up to 2x cheaper than GitHub's. We'll be very happy to have you on board.

**Comment by andreaTP** [comment]
Hi @kgantchev and thanks for your proposal, I'll wait for this repo maintainer's feedback and guidance 👍

**Comment by sbc100** [comment]
If somebody wants to send a PR that does this (but doesn't cost anything) feel free to do so.

In the mean time it seems reasonable to suggest that folks just use homebrew (or for more complex use cases like your just build your own binaries).

**Comment by keithw** [comment]
My own opinion is that I'd love to focus on having our deliverable be source code (like a typical old-school FLOSS project), and let downstream distributors (Linux distributions, PPAs, MacPorts, Homebrew, etc.) be the ones to prepare binaries. If Homebrew isn't preparing binaries in a way that serves the needs of Mac users, that seems like a great topic to bring up with them...

But, sure, if there's a PR that makes people happy and doesn't cost us anything, great.

**Comment by andreaTP** [comment]
@kgantchev I attempted to run on FlyCI:
https://github.com/andreaTP/wabt/actions/runs/7658941205/job/20872958046#step:2:6

Apparently, the CI definition needs many more tweaks than I initially thought, this is very low priority for me, if you want to pick it up it would be great!

**Comment by kgantchev** [comment]
@andreaTP 

[I think I got the setup correctly](https://github.com/kgantchev/wabt/actions/runs/7659231113/job/20873911935), but some of the tests are not passing. Perhaps one of the other (more experienced) contributors can pick it up from here?

**Comment by keithw** [comment]
Looks like only two tests are failing, both related to SIMD. But we seem quite close.

The simd_address failure is expected as we have a TODO for this (https://github.com/WebAssembly/wabt/blob/main/src/template/wasm2c_simd.declarations.c#L6); somebody will need to give us the appropriate asm constraint on arm64.

The simd_i8x16_arith2 failure is less expected and seems to indicate an arm64 issue with the simd-everywhere library that wasm2c uses; I would try updating the `third_party/simde` submodule to the latest simd-everywhere commit, and if that fixes it, great. Otherwise somebody needs to report this upstream to https://github.com/simd-everywhere/simde

**Comment by kgantchev** [comment]
Thanks @keithw... I trust that you guys got it from here. 

The [change is pretty simple](https://github.com/kgantchev/wabt/pull/1/files) tho.

**Comment by keithw** [comment]
I think we probably could talk ourselves into merging the CI change this without the tests 100% passing on arm64 yet, but somebody needs to submit it as a Pull Request for me to review it.

**Comment by kgantchev** [comment]
@keithw I made a [draft PR](https://github.com/WebAssembly/wabt/pull/2373). I'm not familiar with your repo so I didn't want to make a PR that looks "silly". One thing to consider before the actual pull request is ready is that the FlyCI app should be installed on this account and it should be granted permissions to this repo, otherwise, none of the FlyCI jobs will be picked up by our workers. The install instructions are in the draft PR. Once that's ready, I'll make the draft into an actual PR>

**Comment by andreaTP** [comment]
M1 runners are now available for open-source projects on GH Action:
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
