### ISSUE TITLE
How to run tests with Travis?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/wabt#365]
I am try to write a Java to WebAssembly compiler [JWebAssembly](https://github.com/i-net-software/JWebAssembly).

I want run tests on my compiled output if it produce the right result on execution. I think I can do this with wasm-interp. How can I run wasm-interp on Travis? Are there any repository like Maven where it is hosted?

**Comment by binji** [comment]
I don't think there is a build of wasm-interp you can download anywhere, but you can build it yourself on travis, just by following the build instructions from the main page ("git clone ...; make" should be enough).

I'm not sure wasm-interp will do exactly what you need, since it mostly exists just to run tests from the WebAssembly spec repo. Specifically, if you want to execute an arbitrary module, it likely won't work because it will want to import functions/globals/etc. that aren't provided. That said, if you produce output that matches the spec interpreter test format (with `assert_return` commands, etc), it will work.

**Comment by Horcrux7** [comment]
I have think to call:
`wasm-interp test.wasm --run-all-exports`

and check the return values. Are there a better toll for testing?

**Comment by binji** [comment]
Yes, that could work. But it will only run exported functions that have 0 parameters. I wanted to add a mechanism for running exported functions directly, but haven't implemented it yet (see #198)

**Comment by Horcrux7** [comment]
Ok, the 0 parameters are a problem. I have not think on it. But for some first test it should work. An alternative can be to work with node.js.

**Comment by binji** [comment]
I'm not sure what version of WebAssembly is in node.js -- it may be too old to use. You can use any of the JavaScript engines that support it; v8, spidermonkey, chakra and jsc all do, if the version is new enough.

**Comment by Horcrux7** [comment]
You are right. Node.js is currently to old. First the coming version 8.0.0 should support the needed V8 version. In the mean time I use the nightly build of Spider Monkey which can be download from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central
