### ISSUE TITLE
Use Abseil for things like string_view?

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/wabt#639]
Abseil (http://abseil.io/) has finally made its escape from the walls of Google, and might now be a great place to get some utilities such as `string_view` (http://abseil.io/docs/cpp/guides/strings), feature testing, backwards C++ compatibility, etc.

**Comment by binji** [comment]
Interesting, I'll take a look!

**Comment by binji** [comment]
Finally got around to trying this out, see https://github.com/WebAssembly/wabt/pull/971. I'm a little hesitant to add a library dependency, but Abseil seems like a good choice. There are quite a few features that we may want to consider using, including `optional`, `variant`, and `Span`.

I also experimented with string-view-lite instead (see https://github.com/WebAssembly/wabt/pull/970), but ran into some MSVC issues. The *-lite libraries are nice because they are all provided as single-headers, so they're easy to use.

**Comment by keithw** [comment]
wabt now uses C++17's `string_view`
