### ISSUE TITLE
spec/wabt behavior difference

### ISSUE THREAD

**Issue by pepyakin** [WebAssembly/wabt#762]
For the following module spec interpreter reports OK, but `wasm2wat` reports 

```
000000a: error: unable to read u32 leb128: string length
```

base64:

```
AGFzbQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAQAHAAA=
```

i'm not sure who is culprit in this case, so cc @rossberg

**Comment by binji** [comment]
It looks like this creates a bunch of custom sections that aren't big enough to have the section name length. `wasm2wat` treats errors in custom sections as real errors, though as discussed in issue #378, it probably would be good to have an option for this.

**Comment by pepyakin** [comment]
hm, binaryen's wasm-opt also fails with this input.

**Comment by rossberg** [comment]
Hah, excellent find! This actually is a bug in the reference interpreter's handling of empty custom sections, see WebAssembly/spec#698. At first I was confused because we actually have tests for that situation. But it turns out that it was only detected indirectly, and if you manufacture just the right byte sequence following the bogus section that would allow the decoder to resync and get past it.

**Comment by binji** [comment]
Closing, as this was a spec interpreter bug, and was fixed.
