### ISSUE TITLE
Unwinding of Branches and Loops

### ISSUE THREAD

**Issue by ahorn** [WebAssembly/wabt#854]
Could I ask a quick question about the [interpreter](https://github.com/WebAssembly/wabt/blob/409d61ef5d485ae2ce783968f290050840e87a22/src/interp.cc)?

It handles `Br` and `BrIf` opcodes by adjusting the program counter (`pc`). The specification for [control instructions](https://webassembly.github.io/spec/core/syntax/instructions.html#control-instructions) says that "[t]aking a branch *unwinds* the operand stack up to the height where the targeted structured control instruction was entered". This unwinding is [formalized](https://webassembly.github.io/spec/core/exec/instructions.html#control-instructions) by repeatedly popping the stack according to the provided label index.

Where is this unwinding happening in wabt? Thank you for your time!

**Comment by binji** [comment]
Sure, thanks for your interest!

The wabt interpreter is implemented as a simple compiler to a stack machine that uses unstructured control flow instead of structured control flow like the normal wasm stack machine. Many of the instructions are the same, but some (such as the control flow instructions) are different. For example, `br` in the interpreter takes an address to branch to instead of a label.

The conversion happens in [binary-reader-interp.cc](https://github.com/WebAssembly/wabt/blob/master/src/binary-reader-interp.cc). The unwinding happens via the `drop_keep` interpreter instruction, which is emitted by [`EmitBr`](https://github.com/WebAssembly/wabt/blob/master/src/binary-reader-interp.cc#L507).

`drop_keep` adjusts the stack by keeping 0 or 1 values, and discarding N values beneath them. Whenever there's a `br`, we know how much to adjust the stack, so the `drop_keep` instruction encodes it directly.

You can take a look at the generated interpreter instructions by running `wasm-interp` with the `-v` flag:

```wasm
(module
  (func $f (param i32) (result i32)
    block $exit
      get_local 0
      br_if $exit
      i32.const 1
      return
    end
    i32.const 2
    return)

  (func (export "test1") (result i32)
    i32.const 0
    call $f)

  (func (export "test2") (result i32)
    i32.const 1
    call $f))
```

```
$ bin/wasm-interp out/test/interp/brif/brif.wasm -v
...
   0| get_local $1
   5| br_unless @15, %[-1]
  10| br @27
  15| i32.const $1
  20| drop_keep $1 $1
  26| return
  27| i32.const $2
  32| drop_keep $1 $1
  38| return
  39| drop_keep $1 $1
  45| return
  46| i32.const $0
  51| call @0
  56| return
  57| i32.const $1
  62| call @0
  67| return
```

All of the functions are grouped together, so `$f` is at `0..38`, `test1` is at `46..56` and `test2` is at `57..67`. The numbers are byte offsets.

Some other differences from wasm instructions: `get_local` is more like a `pick`, that reads a value on the stack, starting from the top. This works because locals are also stored on the stack. Also, the `i32.const` instruction always stores its immediate value directly as 4 bytes. There are some other differences too, but I can't remember them right now. :-)

**Comment by ahorn** [comment]
A very neat design! Many thanks also for your detailed answer.
