### ISSUE TITLE
Integer values not allowed in data section

### ISSUE THREAD

**Issue by mtharrison** [WebAssembly/wabt#881]
I'm not great at reading this kind of formal grammar but it looks like I should be able to write this according to the docs here https://webassembly.github.io/spec/core/text/values.html#strings:

```
(module
    (memory (import "js" "mem") 1)
    (data (i32.const 0) 123))
)
```

However I get the error:

```
test.wat:3:25: error: unexpected token 123, expected ).
    (data (i32.const 0) 123))
```

I can workaround by instead doing:
```
(data (i32.const 0) "\7b"))
```

But how come the first one doesn't work?

**Comment by binji** [comment]
The data section contents [must be a datastring](https://webassembly.github.io/spec/core/text/modules.html#data-segments), which is just a concatenation of strings, and a string must be surrounded by `"`.

You can try out the [spec interpreter](https://github.com/WebAssembly/spec/tree/master/interpreter) to see that it gives a similar error:
```
$ cat test.wat
(module
    (memory (import "js" "mem") 1)
    (data (i32.const 0) 123))
)
$ ./wasm test.wat
test.wat:3.25-3.28: syntax error: unexpected token
```

We could modify the spec to allow numbers, but in general have been pretty conservative about adding features to the text format. Typically that has been because WebAssembly isn't meant to be written by hand, and because it's been an easy way to avoid bikeshedding. :-)
