### ISSUE TITLE
Writing to non-mutable global variables passes validator

### ISSUE THREAD

**Issue by nomeata** [WebAssembly/wabt#894]
This buggy (the global is not not marked as `mut`) wasm program
```
(module 
  (type $foo.ty       (func)) 
  (global $g i32 (i32.const -1)) 
  (func $foo (type $foo.ty) 
     (set_global $g (i32.const 1)) 
  ) 
  (export "foo" (func $foo)) 
)
```
compiles to `.wasm`, and that files, passes the `wasm-validate`, but gets rejected by the V8 module validator.

**Comment by binji** [comment]
Thanks for finding this! It looks like this has been a bug for a long time, but it was partially hidden because there are two somewhat separate validators in wabt and the spec test that checks this is only run on one of the validators.

We should probably run the other validator over all modules and `assert_invalid` modules as well.

**Comment by binji** [comment]
The two validators are shared now.
